sme_finance_application_schema/finance_application_v1

Support for brand on finance_application_v1

---

sme_finance_application_schema/finance_application_v2
sme_finance_application_schema/lender_v4
sme_finance_application_schema/sme_contact_v2
sme_finance_application_schema/sme_v4

* moves company_number from sme_v3 to sme_contact_v2
* Corrects partnership sizes

creates lender_v4 and sme_v4

---

sme_finance_application_schema/finance_application_v3
sme_finance_application_schema/sme_contact_v3

This one isn't controversial in my opinion - addresses #16

Adds validation required by bank referral scheme to sme_contact

---

sme_finance_application_schema/sme_contact_v3

Removes several non-required fields

---

sme_finance_application_schema/sme_contact_v3
sme_finance_application_schema/sme_v4

Escapes slash in sic code validation

---

sme_finance_application_schema/sme_v4

multiple added to enum

---

sme_finance_application_schema/batch_response_v1
sme_finance_application_schema/finance_application_response_v1

Fies error in response objects

---

sme_finance_application_schema/finance_application_v2

Adds in unique_identifier as a required field

---

sme_finance_application_schema/batch_application_v1
sme_finance_application_schema/batch_response_v1
sme_finance_application_schema/entity_v1
sme_finance_application_schema/finance_application_v1
sme_finance_application_schema/finance_application_v2
sme_finance_application_schema/finance_application_v3
sme_finance_application_schema/finance_need_v1
sme_finance_application_schema/person_v1
sme_finance_application_schema/test.py

It uses links and  definitions properly

Fixes schema urls

---

sme_finance_application_schema/entity_v1
sme_finance_application_schema/finance_application_v3
sme_finance_application_schema/finance_need_v1

fields needed for the proposal

adds missing fields

---

sme_finance_application_schema/entity_v1
sme_finance_application_schema/finance_application_v3
sme_finance_application_schema/finance_need_v1

Stuff that renames properties, changes requirements and moves stuff around.

Bigger changes

---

sme_finance_application_schema/translations.py

I mean I think that's what this does.

Remove director limit for SME translation 

---

sme_finance_application_schema/entity_v1
sme_finance_application_schema/sme_v5
sme_finance_application_schema/translations.py

https://app.clubhouse.io/fundingoptions/story/2708/add-monetary-value-of-outstanding-ccjs-to-the-matching-engine

adds ccj value

---

sme_finance_application_schema/translations.py

applicant['addresses'][] is legit.

deals with an empty list in applicant addresses

---

sme_finance_application_schema/entity_v1
sme_finance_application_schema/sme_v5

https://app.clubhouse.io/fundingoptions/story/3223

adds date_of_first_filed_accounts to sme_v5 and entity_v1

---

examples.py
sme_finance_application_schema/entity_v1
sme_finance_application_schema/sme_v5
test.py

https://app.clubhouse.io/fundingoptions/story/3223

removes date of first filed accounts

---

sme_finance_application_schema/translations.py
test.py

https://app.clubhouse.io/fundingoptions/story/2533/fix-translations-for-address-line-2-in-finance-application-v3-and-contact-v3
@cybojenix can't remember if we're not doing this for a reason - looks like an oversight to me.

translates address_line_2 into locality_name

---

sme_finance_application_schema/examples.py
sme_finance_application_schema/translations.py
test.py

Supports the lendermatcher data_providers app by:
- Allowing translation of incomplete finance applications
- Exposing examples.py in the package

Changes for data_providers

---

sme_finance_application_schema/actor_v1
sme_finance_application_schema/address_v1
sme_finance_application_schema/aggregated_actors_v1
sme_finance_application_schema/entity_v1
sme_finance_application_schema/finance_application_v3
sme_finance_application_schema/finance_need_v1
sme_finance_application_schema/person_v1

https://app.clubhouse.io/fundingoptions/story/3812/add-support-for-finance-application-v3-to-referral-api-endpoint-common-views-api-finance-application
A smaller PR that just contains the necessary stuff for finance_application_v3.
We can work out the rest later

adds finance_application_v3 and components

---

sme_finance_application_schema/batch_application_v1
sme_finance_application_schema/batch_response_v1
sme_finance_application_schema/finance_application_v1
sme_finance_application_schema/finance_application_v2

These are never used, so remove them to avoid confusion

remove redundant definition blocks

---

README.md
sme_finance_application_schema/entity_v1
sme_finance_application_schema/sme_v5
sme_finance_application_schema/tests/fixtures.py
sme_finance_application_schema/translations.py

Chores:
* Updates Readme
Features:
* Adds count_of_all_ccjs
* Adds count_of_unsatisfied_ccjs

Readme and count of CCJs

---

sme_finance_application_schema/tests/fixtures.py
sme_finance_application_schema/tests/test.py
sme_finance_application_schema/translations.py

https://app.clubhouse.io/fundingoptions/story/4716/500-error-on-apienquiry-admin-page

Support sme_v3 and sme_contact_v2

---

sme_finance_application_schema/tests/test.py
sme_finance_application_schema/translations.py

Bugs:
* Deals with data completion errors when translating objects from sme_contact_v2 and v3 to person_v1 and address_v1

More robust telephone

---

sme_finance_application_schema/tests/test.py
sme_finance_application_schema/translations.py

This ensures we can translate back from a finance_application_v3.

Remove backfill

---

sme_finance_application_schema/tests/fixtures.py
sme_finance_application_schema/tests/test.py
sme_finance_application_schema/translations.py

Features:
* Allows the removal of backfilled values from finance_application_v3 when translating back to sme_contact_v2/3

Release PR

---

sme_finance_application_schema/entity_v1
sme_finance_application_schema/person_v1
sme_finance_application_schema/sme_contact_v2
sme_finance_application_schema/sme_contact_v3
sme_finance_application_schema/sme_v5
sme_finance_application_schema/tests/fixtures.py
sme_finance_application_schema/tests/test.py
sme_finance_application_schema/translations.py

schema modification
